name: flores_eval
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pip:
    - transformers>=4.30.0
    - datasets>=2.12.0
    - accelerate>=0.20.0
    - sentencepiece
    - sacrebleu>=2.3.0
    - sacremoses
    - nltk
    - tqdm
    - requests
    - beautifulsoup4
    - lxml
    - omegaconf>=2.3.0
    - hydra-core>=1.3.0
    - hydra-colorlog
    - hydra-optuna-sweeper
    - submitit
    - tensorboard
    - wandb
    - mlflow
    - optuna
    - pytorch-lightning
    - torchmetrics
    - scipy
    - plotly
    - psutil
    - pyyaml
    - toml
    - click
    - rich
    - typer
    - pydantic
    - dataclasses-json
    - python-dotenv
    - gitpython
    - packaging
    - setuptools
    - wheel
    - black
    - isort
    - flake8
    - pytest
    - pytest-cov
    - pytest-mock
    - coverage 